name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@master
      
      - name: "Install pnpm"
        uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.10
      - name: "Install Production and Development Dependencies"
        run: "pnpm install"
      
      - name: "Export a Static Build"
        run: "npm run export"
      - name: "Deploy Hosting"
        run: "npm run firebase:deploy:hosting"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}